### ISSUE TITLE
fog bug

### ISSUE THREAD

**Issue by maxxgamer210** [kyber-6/fantasy-mc-fabric-modpack#34]
### Describe the bug

I can only see what is far from me in minecells:promenade dimension

### Reproduction Steps

only happens when entering the dimension

### Screenshots

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/146362293/2c145f07-6bee-4338-b93c-5f64eb79276b)

### Mod pack version

v15.6

**Comment by kyber-6** [comment]
Try disabling the **Chunks fade in** mod.

**Comment by maxxgamer210** [comment]
didnt solve

**Comment by kyber-6** [comment]
I have not encountered this before, maybe @KevzCz knows.

**Comment by KevzCz** [comment]
relogging/reinstall the pack 
first time seeing this problem

**Comment by maxxgamer210** [comment]
I already tried reinstalling the mod pack with a newer version and it still didn't work

Could this be a conflict with curse forge?

**Comment by kyber-6** [comment]
It is most probably an issue with your graphics card. Make sure you are running the latest drivers.

**Comment by kyber-6** [comment]
Then this beats me. Report this to the developer of MineCells, they might be able to help you.

**Comment by maxxgamer210** [comment]
ok i'll try

**Comment by maxxgamer210** [comment]
Nevermind, probably in some update the owner of the mod can resolve this
