### ISSUE TITLE
Gravestone

### ISSUE THREAD

**Issue by Kallinx12** [kyber-6/fantasy-mc-fabric-modpack#35]
### Describe the bug

When you die in the water, your gravestone breaks and becomes a placeable item but you can't get anything out of it, everything is completely gone

### Reproduction Steps

Die in water with stuff in your inventory, go to your grave and it's a floating item. Pick it up, place it, and break it. You get nothing

### Mod pack version

1.20.1

**Comment by Ruxz1** [comment]
i had this issue too

**Comment by KevzCz** [comment]
Issue has been fixed but the 1.4.0 update will change from forgotten graves to you’re in grave danger
