### ISSUE TITLE
Stick = Adamantine Sword

### ISSUE THREAD

**Issue by m-adking** [kyber-6/fantasy-mc-fabric-modpack#36]
### Describe the bug

Putting a single stick in the crafting table where you would normally put one to craft a sword results in being able to craft an Adamantine sword.

### Reproduction Steps

Get a stick and crafting table, put the stick in the bottom-most middle spot.

### Screenshots

![Screenshot_4](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/147436855/70217e54-abcd-4ebc-b057-27d1ffabddec)

### Mod pack version

v16.1

**Comment by ShyGuyKaii** [comment]
Hey! Not Kyber, but pretty sure this is intended. If you craft the sword with the stick, it will be removed from your inventory, and you will get an ">:{" (angry face) in the chat. That's what happened when I tried.
