### ISSUE TITLE
Quests do not work on the latest versions. 

### ISSUE THREAD

**Issue by Imtwiii** [kyber-6/fantasy-mc-fabric-modpack#38]
### Describe the bug

For all of the 1.20.1 versions of the mod pack downloaded from curseforge for basic the quests are not the same compared to the 1.19 versions a large majority of them are missing, books that should tell you more do not spawn in. The quest book has 1 story quest: getting started which is auto completed by you being given a sword.

### Reproduction Steps

Download any of the recent fabric versions for 1.20.1 off of curseforge

### Mod pack version

v1.0.0 - 1.1.5

**Comment by KevzCz** [comment]
1.19.2 is different from 1.20.1, we decided to start fresh and redo all the quests for 1.20.1
