### ISSUE TITLE
Whole world freezing

### ISSUE THREAD

**Issue by Potatoe69** [kyber-6/fantasy-mc-fabric-modpack#40]
### Describe the bug

While playing Fantasy mc world freezes after a lag and literally nothing is working besides smoke from torches (destroyed items dont drop, mobs just stay in one place and your character never consumes anything and world doesnt render)
Happened to my 2 worlds now and i cant repair it 

### Reproduction Steps

1.Play for a 4-6 hrs
2.lag
3.broken, frozen

### Mod pack version

1.14.22

**Comment by KevzCz** [comment]
There are no modpack version 1.14.22, please also provide the logs as well
