### ISSUE TITLE
Doors and trapdoors not loading (server=

### ISSUE THREAD

**Issue by Raso93** [kyber-6/fantasy-mc-fabric-modpack#41]
### Describe the bug

Basically any of us can´t see the doors or the trapdoors until we interact with them. Some trapdoors become visible once you get close enough, but most of them are invisible.

This doesnt´t happen with 3 tall doors

### Reproduction Steps

Pre set //crafted trapdoors and doors 

### Screenshots

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/39592088/8545fadd-f6f4-4d3e-a5e0-8c7b65691c72)
![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/39592088/1a4f4cb9-f222-43cd-8810-548a1e490d0d)

### Mod pack version

1.1.3 // 1.1.5

**Comment by Volinock** [comment]
I second this issue. happened today on a clean install of both server and 3 separate clients with the same issue.

Unfortunately I cant figure out the reason behind it.

**Comment by Mobuis** [comment]
Link to this mod : https://modrinth.com/mod/pandas-extra-details
The issue on the mod : https://github.com/PandaDap2006/Pandas-Extra-Details/issues/20

**Comment by KevzCz** [comment]
I removed the mod from the modpack so now it shouldnt cause any issues
