### ISSUE TITLE
Faulty shield Behaviour

### ISSUE THREAD

**Issue by Theta-Line** [kyber-6/fantasy-mc-fabric-modpack#44]
### Describe the bug

Shields do not function at all when holding an item in the main hand, but function as normal when the main hand is empty, or holding he shield itself
The failed functionality includes blocking, the charge ability of the crusader class, the "on shield block" effects of the crusader class, and possibly every other "on shield-block effect", as well as the shield bash/charge implemented by the shield overhaul

### Reproduction Steps

1. Grab _any_ shield and _any_ item from the creative menu
2. Equip shield in off-hand, and hold item in main hand
3. Enter survival mode, go up to a hostile mob, and hold block while the item is in the main hand
4. shield will not block any attack

### Screenshots

multiple clips taken in a singleplayer testing world to verify the extent of the issues

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/77c2dc2d-c557-4218-a58a-71be8025e3be

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/871fb43a-bfd4-420b-8ad8-4149c35611ca

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/df76cea4-76ea-400d-906d-74ae6a989a8c

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/5ae65cfc-6db7-4bc2-ad8e-086abe34e12f

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/9a956e90-436c-4876-a74f-e698ee48b1b3

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/309ef148-c9b0-48c6-8f04-2784547137a9

https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/15679518/7b4cca59-6b0a-4ae0-b937-fa1630642448

### Mod pack version

Fantasy MC Fabric v1.2.0 for MC 1.20.1

**Comment by Theta-Line** [comment]
As of Version 1.3.0 of the 1.20 version of the modpack, shield behaviour has changed again, this time, when activating a shield with an empty hand, it functions normally, even if you switch to holding an item
but if activated with an item in hand, it still does not function, even when switching to an empty hand, this is unlike the prior behaviour where it worked when switching from a full hand, to an empty hand

**Comment by KevzCz** [comment]
Hello! Sorry for the late reply. I will check this out if 1.4 has the same issue as 1.3
