### ISSUE TITLE
text, fonts are blocky

### ISSUE THREAD

**Issue by reak6896** [kyber-6/fantasy-mc-fabric-modpack#48]
### Describe the bug

so every text/ font in every single menu is blocky i can provide screenshot
i tried a lot of things to fix this thing i changed the language withoutthe ability to read i deleted every texture pack i enabled every texture pack, but therew was also a problem with the texture packs although i enable it and click done and wait for the loading screen and go back to the resource pack menu its not enabled i tries thesse a lot of times, i deleted iris and deleted every shader pack, i replaced fabric api with an older one for 1.20.1 btw im on 1.20.1 fabric

### Reproduction Steps

please fix this issue or tell me a way to fix it

### Screenshots

![2024-02-01_12 17 48](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/158440832/266121d2-d809-46bc-b189-1bcd84f616f3)
![2024-02-01_12 19 40](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/158440832/7ed858ef-b634-4bb4-8205-27cabb58350c)
![2024-02-01_12 16 53](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/158440832/794cdd4b-1f8d-45d8-85ba-b46939f86487)

### Mod pack version

1.20.1

**Comment by KevzCz** [comment]
go inside your world and F3+T or restart the instance
