### ISSUE TITLE
Biome titles won't go away

### ISSUE THREAD

**Issue by webby-or-Lavvi** [kyber-6/fantasy-mc-fabric-modpack#50]
### Describe your suggestion

Respectfully, if I see one more biome announcement the next time I step into a new biome, that might just be my 13th reason. I am going insane. Please just place it anywhere but the dead center of the screen it's so distracting. Either that or please tell me how I can get rid of it.
![image_2024-02-12_120712837](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/146290845/7adc8b2c-da34-46a0-9ad0-b153e10b3fec)

**Comment by KevzCz** [comment]
Traveller Titles
