### ISSUE TITLE
All mobs will not drop loot or XP

### ISSUE THREAD

**Issue by jpasta44** [kyber-6/fantasy-mc-fabric-modpack#52]
### Describe the bug

None of my mobs are dropping loot or xp, hostile mobs and passive. It seems like this issue occurs when I add mods to the pack, but even if I take those mods out, the issue still persists. /gamrule doMobLoot and /gamerule doEntityDrop do not fix the issue.

### Reproduction Steps

To reproduce this issue, it seems like you either have to go into creative mode on a world, or add a mod to the pack and the issue will happen. Playing on 1.20.1 fabric.

### Screenshots

Not much to be said here, the mobs just don't drop anything.

### Logs & crash-reports

The game doesn't crash, mobs just won't drop loot, even if I create a new world or duplicate the profile. I'm not a coder by any means :)

### Mod pack version

Fantasy MC 2.3.0 (1.20.1)

**Comment by jpasta44** [comment]
Okay I think I found the problem, I had a most recent version of bumblezone, when I changed it to a previous 1.20 version it fixed the problem!

**Comment by KevzCz** [comment]
Please don't ask us for help if you added mods into FantasyMC. We may be able to help you with stuff we're familiar with but this place is for help ABOUT FantasyMC.
