### ISSUE TITLE
server laggin when it have more that 1 person connected

### ISSUE THREAD

**Issue by EuSoJao** [kyber-6/fantasy-mc-fabric-modpack#53]
### Describe the bug

i have a server that runs perfectly when only 1 person is connected but as soon as a second player connect tps goes down

### Reproduction Steps

a second player connects to the server

### Screenshots

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/89408008/9b88bd3d-073a-4cc9-9c61-c0e86466a410)

### Logs & crash-reports

spark log https://spark.lucko.me/TlgbuHRg47

### Mod pack version

2.4.0

**Comment by rruy-dev** [comment]
Running a a Modded MC Server with this many mods (350+) can be very taxing for a server, its not nearly as easy as Vanilla MC.
Especially doing things like Chunk Generation for multiple people in a modded environment... RAM is especially important for Chunk Generation.

What are the Specs of the server?
I would recommend 8gbs RAM to start, and then an additional 2 per player.

Do you have access to a panel that shows all the statistics of the servers hardware usage?
   Example being, Task Manager on a machine if  you have personal access to it, or if you are using a VPS. 
   Or server hosters like Bisect Hosting offer a Performance Panel where you can see the usage of all the hardware.
 Consider checking this to see which part of the machine you should invest in upgrading.

**Comment by KevzCz** [comment]
Try lowering the server render distance as well as using chunky for pregeneration so that its not as taxing as loading new chunks as you play
