### ISSUE TITLE
Game crash while exploring

### ISSUE THREAD

**Issue by GamerelleGirl** [kyber-6/fantasy-mc-fabric-modpack#54]
### Describe the bug

As I was exploring in my world, the game froze and crashed. According to the crash report, there was an "Exception ticking world".  I suspect it is a chunk-loading error?

### Reproduction Steps

Each time I reload the save it crashes as soon as the chunks begin loading. It happens on every load and my save is unplayable :(

### Logs & crash-reports

[crash-2024-03-09_20.50.06-server.txt](https://github.com/kyber-6/fantasy-mc-fabric-modpack/files/14548764/crash-2024-03-09_20.50.06-server.txt)

### Mod pack version

2.4.2

**Comment by rruy-dev** [comment]
According to the log, this is an issue generating a Loot Table for a Loot Chest.

1. What environment where you playing in, SinglePlayer, Private Server, or Public Server?

2. If its a world directly accessible to you, do you know how to use a tool like Amulet ( a world editor for manipulating worlds outside of Minecraft itself ) ?
You can use a tool like this search for, find the Loot Chest, and delete it, to fix the issue.

3. Also after you fix the issue, consider updating to a later version of the Pack, as I think the cause of this was resolved. 
Read the changelogs when you update! Or you may be confused when changes are made regarding gameplay.

**Comment by KevzCz** [comment]
Yeah make a back up of your world and try updating from 2.4.2 to 2.6.1 HF#2
