### ISSUE TITLE
Reforgeing

### ISSUE THREAD

**Issue by jds222** [kyber-6/fantasy-mc-fabric-modpack#55]
### Describe the bug

For some reason it wont let me put amethyst in the anvil to reforge. 

### Reproduction Steps

restarted the game multiple times

### Mod pack version

2.5.0

**Comment by rruy-dev** [comment]
The Tiered Equipment mod was changed from TieredZ, to Kev's Tierify Modifiers
https://www.curseforge.com/minecraft/mc-mods/kevs-tierify-modifiers
A mod made with Fantasy MC Fabric in mind, and has more activity in its development.

Being an extension of Tierify, Reforging is equips no longer uses Amethyst at all. 
Different Tiers are accessed by Different materials.
Information for that can been found in Tierify's documentation / on it's Curseforge page.
https://www.curseforge.com/minecraft/mc-mods/tierify
