### ISSUE TITLE
Blaze king quest not being completed

### ISSUE THREAD

**Issue by Cris1109** [kyber-6/fantasy-mc-fabric-modpack#59]
### Describe the bug

As the title suggest, i'm trying to complete the chapter 3 "find the king's residence", i already went to a tower and killed a blaze king, but the quest is not set as "complete" for some weird reason

### Reproduction Steps

went to a blaze king tower, climb it, kill the boss, nothing happens, tried again 3 times, nothing as well

### Screenshots

![imagen_2024-03-23_142647681](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/164677150/226b1a63-402e-450d-99f9-e04234f0bd63)
![imagen_2024-03-23_142701378](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/164677150/69937be7-f398-4c6b-909d-471651d58263)

### Mod pack version

lastest 2.7.1

**Comment by KevzCz** [comment]
Removed as of the latest version
