### ISSUE TITLE
Failed to clean up cached files

### ISSUE THREAD

**Issue by BombShellReaper** [kyber-6/fantasy-mc-fabric-modpack#60]
### Describe the bug

![Eroor Message](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/165164911/4b211676-63c3-4537-8399-821688da3694)

### Reproduction Steps

It is consistent 

### Logs & crash-reports

Is there is a way to disable this? I don't want to fumble around in the script to root this out without knowing what I am looking for. Thank you

### Mod pack version

Fantasy MC Fabric-2.7.1 SP

**Comment by BombShellReaper** [comment]
If there is a way to disable this I would be grateful, I don't want to fumble around in the script to root this out without knowing what I am looking for. Thank you

**Comment by KevzCz** [comment]
You can probably find a mod that cleans up logs
