### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by DjallenDias** [kyber-6/fantasy-mc-fabric-modpack#63]
### Describe the bug

When I try to open the modpack, it loads a little and shows that there was an incompatibility error between the mods

### Reproduction Steps

Launcher: tlauncher
MC version: 1.20.1 - Fabric
OS: Manjaro Linux
Java: java-17-openjdk

### Logs & crash-reports

[latest.log](https://github.com/kyber-6/fantasy-mc-fabric-modpack/files/14818237/latest.log)

### Mod pack version

2.7.1

**Comment by KevzCz** [comment]
We do not support TLauncher
