### ISSUE TITLE
barrel not generating loot (Bisect hosting server)

### ISSUE THREAD

**Issue by pumpkinpietortis** [kyber-6/fantasy-mc-fabric-modpack#65]
### Describe the bug

The loot table isn't generated, and upon opening the barrel, it is empty. The chest generated in the structure is fine though. The structure is Pillager Outpost Mountain by Ctov

### Reproduction Steps

Go to the structure Pillager Outpost Mountain by Ctov and open the barrel shown in the picture.

### Screenshots

![Untitled](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/165898232/0b4f2faf-a492-43b8-a498-65edf48b7a09)

### Logs & crash-reports

This is the server log.

[latest.log](https://github.com/kyber-6/fantasy-mc-fabric-modpack/files/14850410/latest.log)

### Mod pack version

1201_2.7.1

**Comment by KevzCz** [comment]
It's possible that this is an issue over on CTOV's side
