### ISSUE TITLE
커멘드 블록 설정 오류

### ISSUE THREAD

**Issue by psh0425** [kyber-6/fantasy-mc-fabric-modpack#66]
### Describe the bug

연쇄 커멘드 블록을 잘못 설정하여 같은 위치로 2명이 동시에 이동이 됩니다. 이동이 불가능 합니다.

### Reproduction Steps

해결 방법 알려주실  수 있으신가요?

### Screenshots

![minecraft](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/102129271/a4812a35-19fd-497e-af29-cf8527052330)

### Mod pack version

1.20.1

**Comment by KevzCz** [comment]
i don't remember adding any tp rewards in here, when exactly did this happen?
