### ISSUE TITLE
Unable to enter nether

### ISSUE THREAD

**Issue by Shhhimmy** [kyber-6/fantasy-mc-fabric-modpack#68]
### Describe the bug

As soon as we enter the portal it gets stuck at loading terrain and then the server crashes and resets for a bit

### Reproduction Steps

We've tried changing nether settings and any fixes the internet provides

### Mod pack version

2.8.1

**Comment by KevzCz** [comment]
stand at the nether portal
chunky world the_nether
chunky center
chunky radius 500
chunky start
