### ISSUE TITLE
Invocation Zombie - Class Revenant

### ISSUE THREAD

**Issue by Temujinnn** [kyber-6/fantasy-mc-fabric-modpack#69]
### Describe the bug

When i want to summon zombies with rotten in my hand, the animation did and the flesh are consume, but the zombie doesnt get summoned. Atleast i can summon squeletton without any problem.

### Reproduction Steps

When i want to summon zombies with rotten in my hand, the animation did and the flesh are consume, but the zombie doesnt get summoned. Atleast i can summon squeletton without any problem.

### Mod pack version

Latest 14/04/24

**Comment by KevzCz** [comment]
mod dev fixed the issue and the update is already on the latest version of the modpack
