### ISSUE TITLE
Poor Server Performance even in already loaded chunks - Entity Issue?

### ISSUE THREAD

**Issue by iduFudi** [kyber-6/fantasy-mc-fabric-modpack#70]
### Describe the bug

My Server seems to be performing poorly, even if no new chunks are being loaded.

The server I rented has 8 cores, 14GBs RAM.

I tried installing a few optimization mods like Krypton and C2E, but the issue still occurs, the server still falls behind a lot.

### Reproduction Steps

According to the Spark reports, it seems to be an Entity issue, however I'm not sure how to isolate it.
https://spark.lucko.me/qnZzKE58Jg
https://spark.lucko.me/YJyyKT6kmu

### Mod pack version

v2.8.1

**Comment by KevzCz** [comment]
Have you tried pregenerating with Chunky?
