### ISSUE TITLE
No binding for Active Power (Secondary)

### ISSUE THREAD

**Issue by hakanai** [kyber-6/fantasy-mc-fabric-modpack#71]
### Describe the bug

Going through the controls I was trying to bind the secondary active power to something, and got this result:

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/43236/d8be964d-5ff6-439c-bdc2-f012ecf492e8)

Also, what is "scancode.0"?

### Reproduction Steps

- Start game
- Options...
- Controls...
- Key Binds...
- Put mouse focus in the search box and start typing "Secondary"
- Click Not Bound
- Input: <kbd>compose</kbd><kbd>g</kbd><kbd>g</kbd>

### Screenshots

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/43236/b98eda8f-7da0-4e17-af9e-878cd3072aa2)

### Mod pack version

v2.8.1

### Environment

Windows 11
WinCompose v0.9.11

**Comment by KevzCz** [comment]
Is this keyboards or controller?

**Comment by hakanai** [comment]
Keyboard

**Comment by KevzCz** [comment]
where would this be?
![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/130611225/36cf4c69-0e18-4a4a-a906-41cb652567a4)

**Comment by hakanai** [comment]
And again here so that the embed works.

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/43236/0f81b65e-e1d9-42fc-9e75-6cb34264d148)

**Comment by KevzCz** [comment]
Then have this worked on other modpacks?

**Comment by hakanai** [comment]
Unsure.

Active Power (Secondary) belongs to which mod? I guess I could look at another pack and see what it's bound to in there.

**Comment by KevzCz** [comment]
Minecraft may not even support compose keys in controls. The mod is Origins, but that said it won’t make a difference since every controls are like the same. Have you tried just using G instead of inputing “compose g g”?

**Comment by KevzCz** [comment]
Maybe just use normal keys since i dont think i can help on a technical level

**Comment by hakanai** [comment]
The issue may rest with the individual mod, I'll check it out.

**Comment by hakanai** [comment]
Yep, verified it with just that mod installed. Oki, I will go and find where their tracker is.
