### ISSUE TITLE
Can see water "splash" or "wave" animations off in the distance, through many solid blocks

### ISSUE THREAD

**Issue by MrGooseExclusive** [kyber-6/fantasy-mc-fabric-modpack#73]
### Describe the bug

For some reason, seemingly down in caves at the very least, while walking around on the surface or digging up some cobble, I'll see distant water splashes and/or waves from seemingly some water off in the distance somewhere. I've tried messing with a couple of mods I thought it might be, but can't seem to figure it out.

Here are some photos circling what I'm talking about, if it wasn't obvious already:

![2024-04-22_01 14 57](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/140072041/2d73aa12-bd2f-4572-b5bc-aa27f58affe9)
![2024-04-22_01 15 01](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/140072041/809f84d6-ee78-4477-b414-5c77ee8bf4ac)
![2024-04-22_01 15 14](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/140072041/910b96ad-c820-4b39-bd6d-6283a0447f53)

### Reproduction Steps

I just play the modpack. I recently reinstalled the entire pack and it's still doing it.

### Mod pack version

2.8.1

**Comment by KevzCz** [comment]
It may be the mod “Wakes” but the mod is kinda unneeded so i’ll temove it from the pack next update

**Comment by KevzCz** [comment]
Removed as of 2.9.2a
