### ISSUE TITLE
Everything's grey when using shaders

### ISSUE THREAD

**Issue by MrGooseExclusive** [kyber-6/fantasy-mc-fabric-modpack#74]
### Describe the bug

Whenever I enable any shaders, whether it be the ones included with the pack or others I've downloaded, they all work but the textures are all grey. Here's photos of what I see from each shader.

**Complementary Reimagined:**
![2024-04-22_01 22 06](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/140072041/2d1b59ce-b568-477b-998f-dc3042d63c63)

**Rethinking Voxels (with falling leaf in the way):**
![2024-04-22_01 22 30](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/140072041/b4d73dd7-1c49-48da-836f-9ad10dc1a600)

**Super Duper Vanilla:**
![2024-04-22_01 22 40](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/140072041/5e18f97b-c911-44c8-9ba1-3207277829e8)

### Reproduction Steps

I enable any shader.

### Mod pack version

2.8.1

**Comment by KevzCz** [comment]
1. What launcher are you using?
2. Did you install any new mods?
3. What are your device’s specs? It may be related to that. Or try tweaking the settings of yours or the shaders settings

**Comment by MrGooseExclusive** [comment]
> 1. What launcher are you using?
> 2. Did you install any new mods?
> 3. What are your device’s specs? It may be related to that. Or try tweaking the settings of yours or the shaders settings

1. Curseforge's Launcher
2. Yes, Optifine (which could be the issue idk), Essential (to play with friends), Leaves Be Gone, and I think that's it.
3. Processor: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz   3.60 GHz / Ram: 16.0 GB / System Type: 64-bit operating system, x64-based processor (Idk what people are usually looking for in terms of specs)

**Comment by KevzCz** [comment]
fantasy mc already have sodium which enables shaders, getting rid of optifine and using sodium will most likely fix the issue
