### ISSUE TITLE
Yeti Origin

### ISSUE THREAD

**Issue by Mitchy19951jz** [kyber-6/fantasy-mc-fabric-modpack#77]
### Describe the bug

I chose the Yeti class, but whenever I go anywhere near any snow I start to get cold. I feel like this is an oversight and as a Yeti, they should have cold resistance.

### Reproduction Steps

1. Pick the Yeti Class
2. Go to snow
3. Freeze

### Mod pack version

2.9.1

**Comment by KevzCz** [comment]
fixed with Medieval Origin's latest update
