### ISSUE TITLE
[Bug] Players and Host Unable To Join Hosted Server

### ISSUE THREAD

**Issue by Sourceshard** [kyber-6/fantasy-mc-fabric-modpack#79]
### Describe the bug

After installing the server files and downloading the clients, attempts were made to connect to the server leading to the following error. No one not even the host can log into the server. 

No modifications were made to the modpack.

Displayed Error:
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2442088 into 3

Relevant issue found through google searches:
https://github.com/FabricMC/fabric/issues/2342

### Reproduction Steps

Run 2.9.3b server, try to join with 2.9.3b client.

### Screenshots

![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/37197624/4fa24fa3-e131-4915-aed7-5fa6f8f57c2c)

### Logs & crash-reports

- Client
[2024-06-12-4.log](https://github.com/user-attachments/files/15812732/2024-06-12-4.log)

- Server
[2024-06-12-7.log](https://github.com/user-attachments/files/15812736/2024-06-12-7.log)

### Mod pack version

[2.9.3b] - 31-5-2024

**Comment by KevzCz** [comment]
from the client log it seems that REI and Zenith attributes are causing some errors?

**Comment by Sourceshard** [comment]
Did not see this until now. Ty for checking it out! :D

**Comment by Sourceshard** [comment]
Also forgot to answer the question you posed in Discord. You asked what I use to run the server. This is the program I use, it is installed on Windows. It runs each server instance in a separate Docker Container.

I use this program to run multiple different game servers.
![image](https://github.com/kyber-6/fantasy-mc-fabric-modpack/assets/37197624/f0799a1b-f583-400e-9019-8aba43a75f6f)

https://cubecoders.com/AMP

**Comment by Sourceshard** [comment]
After updating all java versions, updating windows, and running the server before transferring files it just worked. :P
