### ISSUE TITLE
Frame Drops/Performance Issue

### ISSUE THREAD

**Issue by Juni0r213** [kyber-6/fantasy-mc-fabric-modpack#84]
### Describe the bug

I started playing in a single-player server and ever since the start, I get frame drops every few seconds or so. Even standing still I get 150 FPS but the game will freeze still. I've tried tinkering with some of the video settings but nothing seemed to improve the issue, it even still freezes on 3 chunks.

### Reproduction Steps

1. Start singleplayer
2. Run around
3. Experience the constant freezing

### Mod pack version

2.9.3b

**Comment by KevzCz** [comment]
What are your specs? How much memory did you allocate for the modpack?

**Comment by Juni0r213** [comment]
6700 XT
i7 CPU
16gb of ram

Memory was allocated around 8190mb when I started having the issue, and I bumped it up to 10216mb to see of there was any changes but there wasn't.

**Comment by KevzCz** [comment]
Could you check your memory using f3 when the lag spike happens? Also check your task manager as well. My laptop has 8gb and it still is doing quite well so i dont really know what could be causing the lag spikes

**Comment by Juni0r213** [comment]
When the lag spike happens, memory usage sits around 40-60%. CPU usage is around 70-80% and GPU was at 20-40%

**Comment by KevzCz** [comment]
Hm maybe try updating your java to 21 iirc? A guy on discord had issues with lag spike but it was very specific and updating java fixed the issue

**Comment by Juni0r213** [comment]
That might work, I'll check it out tomorrow. 👍

**Comment by Juni0r213** [comment]
It seems like updating Java took care of the majority of the problem, I do still get lag spikes when in my inventory though which is strange. Unless I downloaded the wrong version, but this has helped.

**Comment by Juni0r213** [comment]
I was able to find a solution to the problem, it has to deal with the Java version. This website made from Fabric has a guide on which one to use. https://fabricmc.net/wiki/player:tutorials:java:windows
